language: minimal

sudo: false

env:
  global:
    - secure: "UuZqRQylmD9ovn4Xx5K3d6yY9DqUoMuOOyuKG9TbOHY98CKjMk8y6fFYZK/Q7e9Qmh8FuM49vn0Zme6W/lgJkwdjIZ4RX+yPVk8H3iXglExgbMa0EVFi/Cvy+x6K+a/ekUtsUcDxuEGruModmiodNiQLtXYU0rQ/aGClWh/NsLbObQpuP9+n3l6brRmzqOIHaPTUShSfydAsMPqyoyt+ha19F6uEQtYcWPWnUQssVuzPUvamlOqT38wbvnt4bqXQR/uZaK1zeZqi4ZDkhKwpBPJe9DUGgpTTsK+bT0DUoOSZApnTHLvNHFTf3OJxq4ZD3+DqQOZD0WczY8n9r8Jw2a+0wU5kcC4LbtL49396ShagpBuHH/JfN8KTe6/fW8TdsqMgJQ/Pfs3GltwWyqusGBC72brFH8h1QHpvj25sREzVtSGnmDVh9IWdZQBxy+a01ZjA6RssNN6feF4spJ/qparhgf7Wh1MY+ZknkeuqvaLhasU6qKnPOUAz1bBUfPJ48KsD/NRmHPPHfVtLQZviGNC0qKrr74nU3Y5h80xNenL5UcjzJcHltwGI7cBSfq/WUBIFy6WPUwUZ3jfEQp9DwXR5iOih3iMbVxWpKzreeyuwDzu29bdrOirAWxtcssLl+sLiNsL7efIVDNVHcT5RKE9r1PeBa45Zv0yyqoIdGkg="

cache:
  directories:
    - $HOME/miniconda

# Removing the directory will remove the env but leave the cached packages
# at $HOME/miniconda/pkgs. That is a win-win because when re-creating the
# env we will download only the new packages.
before_cache:
  - rm -rf $HOME/miniconda/envs/IOOS

matrix:
  fast_finish: true
  include:
    - name: "notebooks"
      os: linux
    - name: "env-linux"
      os: linux
    - name: "env-osx"
      os: osx
    - name: "publish"
      os: linux

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      URL="https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh"
    elif [ "$TRAVIS_OS_NAME" == "linux" ] ; then
      URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"
    fi
    echo ""
    if [ ! -f $HOME/miniconda/bin/conda ] ; then
      echo "Fresh miniconda installation."
      wget $URL -O miniconda.sh
      rm -rf $HOME/miniconda
      bash miniconda.sh -b -p $HOME/miniconda
    fi
    export PATH="$HOME/miniconda/bin:$PATH"
    conda update conda

install:
  - travis_wait conda create --name IOOS --file .binder/conda-linux-64.lock
  - source activate IOOS

script:
  # Test published notebooks.
  - if [ $TRAVIS_JOB_NAME == "notebooks" ]; then
      travis_wait pytest --nbval --nbval-lax notebooks/ ;
    fi

  - if [ $TRAVIS_JOB_NAME == "env-linux" ]; then
      python -c 'import gdal; print(dir(gdal))' ;
    fi

  - if [ $TRAVIS_JOB_NAME == "env-osx" ]; then
      python -c 'import gdal; print(dir(gdal))' ;
    fi

  # Publish the notebooks.
  - if [ $TRAVIS_JOB_NAME == "publish" ]; then
      set -e ;
      conda install doctr ;
      pushd webpage && python make_index.py && popd ;
      find notebooks/ -maxdepth 1 -name \*.ipynb -print0 | xargs -0 -n1 jupyter nbconvert --template-file jupyter-jekyll.tpl --config nbconvert_config.py ;
      python -m doctr deploy --key-path github_deploy_key_ioos_notebooks_demos.enc --built-docs webpage/ . ;
    fi
